apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "docstest"
  description: "test docs template"
  annotations:
    github.com/project-slug: mitchellhyde/docstest
    backstage.io/techdocs-ref: url:https://github.com/mitchellhyde/docstest
spec:
  type: documentation
  lifecycle: experimental
  owner: "mitchellhyde"
